# Generated by Django 4.2.28 on 2026-03-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFormular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dozentenname', models.CharField(max_length=50)),
                ('kursnummer', models.CharField(max_length=20)),
                ('zufriedenheitswert', models.IntegerField()),
                ('allgemeiner_bewertungswert', models.IntegerField()),
                ('kompetenzwert', models.IntegerField()),
                ('ilias_modul_bewertung', models.IntegerField()),
                ('selbsteinschaetzungswert', models.IntegerField()),
                ('sonstiges', models.TextField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('kurs', models.ForeignKey(db_column='kursname', on_delete=django.db.models.deletion.CASCADE, to='feedback_azubi.kurs')),
            ],
            options={
                'db_table': 'feedback_formular',
            },
        ),
    ]
