# Generated by Django 4.2.28 on 2026-03-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_kurs_options'),
        ('feedback_azubi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackformular',
            name='kurs',
            field=models.ForeignKey(db_column='kursname', on_delete=django.db.models.deletion.CASCADE, to='dashboard.kurs'),
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
    ]
