# Generated by Django 4.2.28 on 2026-03-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurs',
            options={'ordering': ['id']},
        ),
    ]
